services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: splash_links
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U splash_links -d splash_links"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "127.0.0.1:5432:5432"

  splash_links:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8081:8081"
    environment:
      SPLASH_LINKS_DB: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/splash_links"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  # in podman, expect ~/.local/share/containers/storage/volumes/splash_links_pgdata/
  pgdata:
