"""W3C PROV-O vocabulary constants and helpers for this project.

All PROV-O terms are locked to the canonical W3C namespace.  Import the
constants from this module instead of writing bare ``http://www.w3.org/ns/prov#``
strings in data files or code.

Usage example::

    from app.modules.prov import WAS_GENERATED_BY, extraction_activity

    act = extraction_activity("run-42", "deepseek-r1:32b", "2026-09-21T00:00:00Z")
    edge = {
        "subject": "matkg:KG-v7",
        "predicate": WAS_GENERATED_BY,
        "object": act["id"],
    }
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Namespace
# ---------------------------------------------------------------------------

PROV_NS: str = "http://www.w3.org/ns/prov#"
"""Canonical W3C PROV-O namespace URI."""

PROV_PREFIX: str = "prov:"
"""Compact prefix used in all data files for PROV-O terms."""


def prov_uri(local: str) -> str:
    """Return the full PROV-O URI for a local name.

    Args:
        local: The local name (e.g. ``"wasGeneratedBy"``).

    Returns:
        Full URI string, e.g. ``"http://www.w3.org/ns/prov#wasGeneratedBy"``.

    Example::

        >>> prov_uri("wasGeneratedBy")
        'http://www.w3.org/ns/prov#wasGeneratedBy'
    """
    return f"{PROV_NS}{local}"


def prov_prefixed(local: str) -> str:
    """Return the compact ``prov:`` prefixed form for a local name.

    Args:
        local: The local name (e.g. ``"Entity"``).

    Returns:
        Compact form string, e.g. ``"prov:Entity"``.
    """
    return f"{PROV_PREFIX}{local}"


# ---------------------------------------------------------------------------
# Class URIs
# ---------------------------------------------------------------------------

ENTITY: str = prov_uri("Entity")
"""prov:Entity — a thing that was produced or used."""

ACTIVITY: str = prov_uri("Activity")
"""prov:Activity — something that happened with optional time bounds."""

AGENT: str = prov_uri("Agent")
"""prov:Agent — a person or software responsible for an activity."""

# ---------------------------------------------------------------------------
# Relation URIs  (used as edge predicates)
# ---------------------------------------------------------------------------

WAS_GENERATED_BY: str = prov_uri("wasGeneratedBy")
"""prov:wasGeneratedBy — an Entity was generated by an Activity."""

USED: str = prov_uri("used")
"""prov:used — an Activity used an Entity."""

WAS_DERIVED_FROM: str = prov_uri("wasDerivedFrom")
"""prov:wasDerivedFrom — an Entity was derived from another Entity."""

WAS_ATTRIBUTED_TO: str = prov_uri("wasAttributedTo")
"""prov:wasAttributedTo — an Entity is attributed to an Agent."""

WAS_ASSOCIATED_WITH: str = prov_uri("wasAssociatedWith")
"""prov:wasAssociatedWith — an Activity was associated with an Agent."""

AT_TIME: str = prov_uri("atTime")
"""prov:atTime — timestamp attached to an ``InstantaneousEvent``."""

STARTED_AT_TIME: str = prov_uri("startedAtTime")
"""prov:startedAtTime — the time at which an Activity started."""

ENDED_AT_TIME: str = prov_uri("endedAtTime")
"""prov:endedAtTime — the time at which an Activity ended."""

# ---------------------------------------------------------------------------
# Compact-prefix aliases  (used in JSON data files)
# ---------------------------------------------------------------------------

PROV_ENTITY: str = prov_prefixed("Entity")
PROV_ACTIVITY: str = prov_prefixed("Activity")
PROV_AGENT: str = prov_prefixed("Agent")

# ---------------------------------------------------------------------------
# Helper constructors
# ---------------------------------------------------------------------------


def extraction_activity(
    run_id: str,
    model: str,
    started_at: str,
    ended_at: str | None = None,
) -> dict:
    """Return a PROV-O Activity node dict for an extraction run.

    The returned dict is compatible with the KG ``nodes`` list format used
    throughout this project.

    Args:
        run_id: Unique run identifier, used to build the node ``id``
            (e.g. ``"run-42"`` → ``"prov:Activity-run-42"``).
        model: Model name / version string (e.g. ``"deepseek-r1:32b"``).
        started_at: ISO-8601 start timestamp string.
        ended_at: Optional ISO-8601 end timestamp string.

    Returns:
        A plain dict with keys ``id``, ``entityType``, ``type``,
        ``model``, ``startedAtTime``, and optionally ``endedAtTime``.

    Example::

        >>> act = extraction_activity("run-1", "gpt-4o", "2026-01-01T00:00:00Z")
        >>> act["entityType"]
        'prov:Activity'
    """
    node: dict = {
        "id": f"prov:Activity-{run_id}",
        "entityType": PROV_ACTIVITY,
        "type": PROV_ACTIVITY,
        "name": f"Extraction run {run_id}",
        "description": f"Term-extraction pass using model {model}.",
        "model": model,
        STARTED_AT_TIME: started_at,
    }
    if ended_at is not None:
        node[ENDED_AT_TIME] = ended_at
    return node


def work_entity(
    doi: str,
    title: str,
    pdf_path: str | None = None,
) -> dict:
    """Return a PROV-O Entity node dict for a Work (paper).

    Args:
        doi: DOI string (used to construct the node ``id``).
        title: Human-readable title of the work.
        pdf_path: Optional local file path to the PDF.

    Returns:
        A plain dict with keys ``id``, ``entityType``, ``type``,
        ``name``, ``doi``, and optionally ``pdf_path``.

    Example::

        >>> e = work_entity("10.1000/xyz123", "A Paper Title")
        >>> e["entityType"]
        'prov:Entity'
    """
    safe_doi = doi.replace("/", "_").replace(":", "_")
    node: dict = {
        "id": f"prov:Entity-Work-{safe_doi}",
        "entityType": PROV_ENTITY,
        "type": PROV_ENTITY,
        "name": title,
        "description": f"Work entity for DOI {doi}.",
        "doi": doi,
    }
    if pdf_path is not None:
        node["pdf_path"] = pdf_path
    return node


def kg_snapshot_entity(path: str, corpus_revision: str) -> dict:
    """Return a PROV-O Entity node dict for a KG snapshot file.

    Args:
        path: Relative or absolute file path to the KG JSON file
            (e.g. ``"storage/kg/matkg_bl1101_v7.json"``).
        corpus_revision: A short corpus revision label or git SHA string.

    Returns:
        A plain dict with keys ``id``, ``entityType``, ``type``,
        ``name``, ``path``, and ``corpus_revision``.

    Example::

        >>> snap = kg_snapshot_entity("storage/kg/matkg_bl1101_v7.json", "v7")
        >>> snap["entityType"]
        'prov:Entity'
    """
    # Derive a stable node ID from the file path
    safe_path = path.replace("/", "-").replace(".", "-").strip("-")
    node: dict = {
        "id": f"prov:Entity-KGSnapshot-{safe_path}",
        "entityType": PROV_ENTITY,
        "type": PROV_ENTITY,
        "name": path.split("/")[-1],
        "description": f"KG snapshot file at {path} (corpus revision {corpus_revision}).",
        "path": path,
        "corpus_revision": corpus_revision,
    }
    return node


def extraction_provenance_edges(
    activity_id: str,
    work_id: str,
    terms_entity_id: str,
) -> list[dict]:
    """Return the three canonical PROV-O edges for an extraction pass.

    The three edges encode:

    1. ``activity prov:used work`` — the activity consumed the source paper.
    2. ``terms prov:wasGeneratedBy activity`` — the extracted terms were produced
       by the activity.
    3. ``terms prov:wasDerivedFrom work`` — the extracted terms are ultimately
       derived from the source paper.

    Args:
        activity_id: Node ID of the extraction Activity (e.g. ``"prov:Activity-run-42"``).
        work_id: Node ID of the source Work Entity (e.g. ``"prov:Entity-Work-10_1000_xyz123"``).
        terms_entity_id: Node ID of the extracted-terms Entity (e.g. ``"matkg:TermsSnapshot-42"``).

    Returns:
        A list of three edge dicts, each with keys ``subject``,
        ``predicate``, and ``object``.

    Example::

        >>> edges = extraction_provenance_edges("prov:Activity-run-1", "prov:Entity-Work-X", "matkg:Terms-1")
        >>> len(edges)
        3
        >>> edges[0]["predicate"] == USED
        True
    """
    return [
        {
            "subject": activity_id,
            "predicate": USED,
            "object": work_id,
        },
        {
            "subject": terms_entity_id,
            "predicate": WAS_GENERATED_BY,
            "object": activity_id,
        },
        {
            "subject": terms_entity_id,
            "predicate": WAS_DERIVED_FROM,
            "object": work_id,
        },
    ]
