# Project Information
site_name: Splash Links
site_description: SQL-backed entity, relationship, and embedding service
site_author: ALS Computing
repo_name: als-computing/splash_links
repo_url: https://github.com/als-computing/splash_links
edit_uri: edit/main/mkdocs/docs/

# Navigation
nav:
- Home: index.md
- Concepts and storage: concepts.md
- API and clients: api.md
- Importing MatKG: importing.md
- Deployment: deployment.md
- Development and testing: test.md
- About: about.md

# Theme and Plugins
theme:
  name: material
  custom_dir: overrides
extra_css:
- assets/als_style.css
extra:
  favicon: overrides/assets/images/favicon.png
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/als-computing

plugins:
- search
